# Generated by Django 3.0.5 on 2020-05-06 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='IIN')),
            ],
            options={
                'verbose_name': 'Black list',
                'verbose_name_plural': 'Black list',
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='IIN')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
            ],
            options={
                'verbose_name': 'The Borrower',
                'verbose_name_plural': 'Borrowers',
            },
        ),
        migrations.CreateModel(
            name='LoanProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_sum', models.PositiveIntegerField(default=0, verbose_name='Minimum loan amount')),
                ('max_sum', models.PositiveIntegerField(default=0, verbose_name='Maximum loan amount')),
                ('min_age', models.PositiveSmallIntegerField(default=0, verbose_name='Minimum age')),
                ('max_age', models.PositiveSmallIntegerField(default=0, verbose_name='Maximum age')),
            ],
            options={
                'verbose_name': 'Loan program',
                'verbose_name_plural': 'Loan programs',
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Loan amount')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('AC', 'Accepted'), ('RE', 'Rejected')], default='CR', max_length=2, verbose_name='Status')),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина отказа')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loan.Borrower', verbose_name='The borrower')),
            ],
            options={
                'verbose_name': 'Loan application',
                'verbose_name_plural': 'Loan applications',
            },
        ),
    ]
