# Generated by Django 3.0.5 on 2020-05-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
    ]
