# Generated by Django 3.0.5 on 2020-05-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20200506_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Rejection reason'),
        ),
    ]
